"""Initial schema

Revision ID: 7f9ff52393e3
Revises: 
Create Date: 2026-03-25 02:00:36.507543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9ff52393e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('llm_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_logs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_logs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_logs_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_logs_status'), ['status'], unique=False)

    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('example_file', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_template_id'), ['template_id'], unique=False)

    op.create_table('template_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'field_name', name='uq_template_field_name')
    )
    op.create_table('extraction_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('extracted_data', sa.Text(), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    with op.batch_alter_table('extraction_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_results_is_reviewed'), ['is_reviewed'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_results_is_reviewed'))
        batch_op.drop_index(batch_op.f('ix_extraction_results_created_at'))

    op.drop_table('extraction_results')
    op.drop_table('template_fields')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_template_id'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))

    op.drop_table('documents')
    op.drop_table('templates')
    with op.batch_alter_table('llm_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_logs_status'))
        batch_op.drop_index(batch_op.f('ix_llm_logs_request_type'))
        batch_op.drop_index(batch_op.f('ix_llm_logs_provider'))
        batch_op.drop_index(batch_op.f('ix_llm_logs_document_id'))
        batch_op.drop_index(batch_op.f('ix_llm_logs_created_at'))

    op.drop_table('llm_logs')
    op.drop_table('app_settings')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_log_action'))

    op.drop_table('activity_log')
    # ### end Alembic commands ###
