"""add columns to template_fields

Revision ID: b289b302a16d
Revises: 7f9ff52393e3
Create Date: 2026-03-25 13:45:37.513728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b289b302a16d'
down_revision: Union[str, None] = '7f9ff52393e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_entity_type'), ['entity_type'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_template_id'), ['template_id'], unique=False)

    with op.batch_alter_table('extraction_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_results_is_reviewed'), ['is_reviewed'], unique=False)

    with op.batch_alter_table('llm_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_logs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_logs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_logs_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_logs_status'), ['status'], unique=False)

    with op.batch_alter_table('template_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('columns', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_fields', schema=None) as batch_op:
        batch_op.drop_column('columns')

    with op.batch_alter_table('llm_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_logs_status'))
        batch_op.drop_index(batch_op.f('ix_llm_logs_request_type'))
        batch_op.drop_index(batch_op.f('ix_llm_logs_provider'))
        batch_op.drop_index(batch_op.f('ix_llm_logs_document_id'))
        batch_op.drop_index(batch_op.f('ix_llm_logs_created_at'))

    with op.batch_alter_table('extraction_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_results_is_reviewed'))
        batch_op.drop_index(batch_op.f('ix_extraction_results_created_at'))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_template_id'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_log_action'))

    # ### end Alembic commands ###
